global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'spring-micrometer'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets:
          - 'discovery-service:8761'
          - 'api-gateway:8080'
          - 'product-service:8081'
          - 'inventory-service:8082'
          - 'order-service:8083'
          - 'payment-service:8084'
